# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               RCLinUS
tagline:             'A project in historical sociology'
description:         'Race, Citizenship, and Labour in the US is a project in historical sociology based at the University of Edinburgh.'
#url:                 http://lanyon.getpoole.com
baseurl:             https://yuji-shimohira-calvo.github.io/RCLinUS/
paginate:            5
gems:                [jekyll-paginate]

# About/contact
#author:
  #name:              Mark Otto
  #url:               https://twitter.com/mdo
  #email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
